version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: notification-pg
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: notification
    ports:
      - "5433:5432"          # 5433, чтобы не конфликтовать с локальным PG
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification -d notification"]
      interval: 5s
      timeout: 5s
      retries: 10

  # опционально, чтобы глазами смотреть БД
  adminer:
    image: adminer:latest
    container_name: notification-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  pgdata: