spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: notification
    password: notification
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # для MVP ок, потом — flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: debug